const categories = {
  "① 四則・等不等号": {
    "±(1)": " \\pm ",
    "∓(2)": " \\mp ",
    "･(3)": " \\cdot ",
    "×(4)": " \\times ",
    "÷(5)": " \\div ",
    "分数(6)": " \\displaystyle \\frac{}{} ",
    "≠(7)": " \\neq ",
    "≤(8)": " \\leq ",
    "≥(9)": " \\geq ",
    "≒": " \\fallingdotseq ",
  },
  "② 括弧・絶対値": {
    "()(1)": " \\left( \n \\right) ",
    "[](2)": " \\left[ \n \\right] ",
    "{}(3)": " \\left\\{ \n \\right\\} ",
    "| |(4)": " \\left| \n \\right| ",
    "‖ ‖(5)": " \\left\\| \n \\right\\| ",
    "〈〉(6)": " \\left\\langle \n \\right\\rangle ",
  },
  "③ 添字・指数・√": {
    "下付き(添字)(1)": "_{} ",
    "上付き(乗数)(2)": "^{} ",
    "√(3)": " \\sqrt{\n} ",
    "n√(4)": " \\sqrt[n]{\n} ",
    "バー(5)": " \\bar{} ",
    "上線(6)": " \\overline{} ",
    "下線(7)": " \\underline{} ",
    "上付き点(8)": " \\dot{} ",
  },
  "④ ギリシャ小文字": {
    "α(アルファ1)": " \\alpha ",
    "β(ベータ2)": " \\beta ",
    "γ(ガンマ3)": " \\gamma ",
    "δ(デルダ4)": " \\delta ",
    "ε(イプシロン5)": " \\epsilon ",
    "ζ(ゼータ6)": " \\zeta ",
    "η(イータ7)": " \\eta ",
    "θ(シータ8)": " \\theta ",
    "ι(イオタ9)": " \\iota ",
    "κ(カッパ)": " \\kappa ",
    "λ(ラムダ)": " \\lambda ",
    "μ(ミュー)": " \\mu ",
    "ν(ニュー)": " \\nu ",
    "ξ(クサイ)": " \\xi ",
    "π(パイ)": " \\pi ",
    "ρ(ロー)": " \\rho ",
    "σ(シグマ)": " \\sigma ",
    "τ(タウ)": " \\tau ",
    "φ(ファイ)": " \\phi ",
    "χ(カイ)": " \\chi ",
    "ψ(サイ)": " \\psi ",
    "ω(オメガ)": " \\omega ",
  },
  "⑤ ギリシャ大文字": {
    "Γ(ガンマ1)": " \\Gamma ",
    "Δ(デルタ2)": " \\Delta ",
    "Θ(シータ3)": " \\Theta ",
    "Λ(ラムダ4)": " \\Lambda ",
    "Π(パイ5)": " \\Pi ",
    "Σ(シグマ6)": " \\Sigma ",
    "Φ(ファイ7)": " \\Phi ",
    "Ω(オメガ8)": " \\Omega "
  },
  "⑥ 積分・微分・三角関数": {
    "∑(1)": " \\displaystyle \\sum_{}^{} ",
    "∫(2)": " \\int ",
    "lim(3)": " \\lim_{x \\to 0} ",
    "微分(4)": " \\frac{d}{dx} ",
    "偏微分(5)": " \\frac{\\partial}{\\partial x} ",
    "log(6)": " \\log ",
    "ln(7)": " \\ln ",
    "無限大(8)": " \\infty ",
    "sin(9)": " \\sin ",
    "cos": " \\cos ",
    "tan": " \\tan ",  
    "∬": " \\iint ",
    "∭": " \\iiint ",
  },
  "⑦ 行列・ベクトル": {
    "[行列](1)": " \\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix} ",
    "(行列)(2)": " \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} ",
    "|行列|(3)": " \\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} ",
    "3要素以上の行列(4)": " \\begin{array}{ccc}a & b & c \\\\ d & e & f \\end{array} ",
    "ベクトル(5)": " \\vec{v} ",
    "u→(6)": " \\overrightarrow{u} ",
    "転置(8)": "^T ",
    "二項(9)": " \\binom{n}{k}"
  },
  "⑧ 書体・太字": {
    "太字(1)": " \\mathbf{} ",
    "イタリック斜体(2)": " \\mathit{} ",
    "ローマン立体(3)": " \\mathrm{} ",
    "カリグラフィ(4)": " \\mathcal{} ",
    "ブラックボード(5)": " \\mathbb{} ",
    "フラクトゥール(6)": " \\mathfrak{} ",
    "displaystyle(7)": " \\displaystyle "
  },
  "⑨ スペース・改行": {
    "小スペース(1)": " \\, ",
    "中スペース(2)": " \\: ",
    "大スペース(3)": " \\quad ",
    "改行用array{添字はrclなど}(4)": "\\begin{array}{rl}\n\n\\end{array} ",
    "改行(5)": " \\\\ \n",
    "array揃え文字(6)": " & ",
    "列インデント(7)": " \\hspace{1em} ",
    "行インデント(8)": " \\vspace{1em} ",
    "phantom(9)": " \\phantom{} "
  },
  "⑩ 集合": {
    "∈(1)": " \\in ",
    "∉(2)": " \\notin ",
    "⊂(3)": " \\subset ",
    "⊃(4)": " \\supset ",
    "∪(5)": " \\cup ",
    "∩(6)": " \\cap ",
    "⊆(7)": " \\subseteq ",
    "⊇(8)": " \\supseteq ",
    "∅(9)": " \\emptyset ",
    "∃": " \\exists ",
    "∀": " \\forall"
  },
  "⑨ 特殊記号": {
    "…(1)": " \\cdots ",
    "~(2)": " \\sim ",
    "≈(3)": " \\approx ",
    "≅(4)": " \\cong ",
    "∴(5)": " \\therefore ",
    "→(6)": " \\rightarrow ",
    "←(7)": " \\leftarrow ",
    "⋮(8)": " \\vdots ",
    "%(9)": " \\% ",
    "⋱": " \\ddots ",
    "∵": " \\because ",    
    "⇔": " \\Leftrightarrow ",
    "↔": " \\leftrightarrow ",
    "⇑": " \\Uparrow ",
    "⇒": " \\Rightarrow ",
    "↦": " \\mapsto ",
    "表水平ライン": "\n\\hline\n",
  },
};

const category_colors = {
  "① 四則・等不等号": "#ffdddd",
  "② 括弧・絶対値": "#ddffdd",
  "③ 添字・指数・√": "#ddeeff",
  "④ ギリシャ小文字": "#fff0aaff",
  "⑤ ギリシャ大文字": "#efffaaff",
  "⑥ 書体・太字": "#f8d8b0",
  "⑦ スペース・改行": "#e0e0e0",
  "⑧ 積分・微分・三角関数": "#f0ddff",
  "⑨ 行列・ベクトル": "#ddffff",
  "⑩ 集合": "#e2f8ffff",  
  "⑪ 特殊記号": "#ffeecc",

};









